[Project]
"Start time" = "2020-1-1 00:00:00.0"
"Simulation duration (min)" = 1
"Loadshape start time" = "2020-1-1 00:00:00.0"
"Step resolution (sec)" = 1
"Max Control Iterations" = 50
"Error tolerance" = 0.001
"Control mode" = "Static"
"Disable PyDSS controllers" = false
"Simulation Type" = "QSTS"
"Project Path" = "C:/Users/alatif/Documents/GitHub/PyDSS/examples/external_interfaces"
"Active Project" = "pydss_project"
"Active Scenario" = ""
"DSS File" = "Master_Spohn_existing_VV.dss"
"DSS File Absolute Path" = false
"Return Results" = false
[[Project.Scenarios]]
name = "helics"
post_process_infos = []

[Exports]
"Log Results" = true
"Export Mode" = "byClass"
"Export Style" = "Single file"
"Export Elements" = true
"Export Event Log" = true
"Export Format" = "h5"
"Export Compression" = true
"Export Data Tables" = false
"Export PV Profiles" = false

[Frequency]
"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

[Helics]
"Co-simulation Mode" = true
"Iterative Mode" = false
"Error tolerance" = 1e-8
"Max co-iterations" = 20
"Federate name" = "pydss_1"
"Time delta" = 1
"Core type" = "ZMQ"
Broker = "127.0.0.1"
"Broker port" = 50000
Uninterruptible = true
"Helics logging level" = 5

[Logging]
"Logging Level" = "DEBUG"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = false

[MonteCarlo]
"Number of Monte Carlo scenarios" = -1

[Plots]
"Create dynamic plots" = false
"Open plots in browser" = true
