[[Loads]]
property = "Powers"
sample_interval = 1
publish = true
store_values_type = "all"

[[Circuits]]
property = "TotalPower"
sample_interval = 1
publish = true
store_values_type = "all"

[[Lines]]
property = "Currents"
name_regexes = ["Line.sw"]
sample_interval = 1
publish = true
store_values_type = "sum"

[[Buses]]
property = "Voltages"
names = ["111-pv", "113-pv"]
sample_interval = 1
publish = true
store_values_type = "all"

[[Vsources]]
property = "Powers"
sample_interval = 1
publish = true
store_values_type = "all"

[[Capacitors]]
property = "states"
sample_interval = 1
publish = true
store_values_type = "all"

[[Transformers]]
property = "tap"
sample_interval = 1
publish = true
store_values_type = "all"

