[[Circuits]]
publish = true
sample_interval = 1
store_values_type = "all"
property = "TotalPower"

[[Lines]]
publish = true
sample_interval = 1
store_values_type = "all"
name_regexes = [ "Line.sw",]
property = "Currents"

[[Loads]]
publish = true
sample_interval = 1
store_values_type = "all"
property = "Powers"

[[Buses]]
publish = true
sample_interval = 1
store_values_type = "all"
names = [ "111-pv", "113-pv",]
property = "Voltages"

[[Capacitors]]
publish = true
sample_interval = 1
store_values_type = "all"
property = "states"

[[Transformers]]
publish = true
sample_interval = 1
store_values_type = "all"
property = "tap"

