[[Loads]]
property = "Powers"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

[[Circuits]]
property = "TotalPower"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

[[Lines]]
property = "Currents"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "sum"
sum_elements = false
sum_groups = []

[[Buses]]
property = "Voltages"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
names = [ "113-pv", "111-pv",]
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

[[Vsources]]
property = "Powers"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

[[Capacitors]]
property = "states"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

[[Transformers]]
property = "tap"
data_conversion = "none"
opendss_classes = []
sample_interval = 1
publish = true
store_values_type = "all"
sum_elements = false
sum_groups = []

